# SPDX-FileCopyrightText: Timothée Ravier <tim@siosm.fr>
# SPDX-License-Identifier: CC0-1.0

name: "Build sysext for Fedora"

env:
  GH_TOKEN: ${{ github.token }}
  RELEASEURL: "https://github.com/${{ github.repository }}/releases/download"

on:
  pull_request:
    branches:
      - "main"
  push:
    tags:
      - "*"
  workflow_dispatch:

# Needed to allow creating a release
permissions:
  contents: write

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-x86_64:
    strategy:
      fail-fast: false
      matrix:
        release: ['41', '42']
    runs-on: "ubuntu-24.04"
    container:
      image: "ghcr.io/travier/sysexts-manager/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    env:
      IMAGE: "quay.io/fedora-ostree-desktops/base-atomic:${{ matrix.release }}"
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v5

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

      - name: "Build sysexts-manager"
        run: |
          cargo build --release
          mkdir -p sysexts-manager/usr/bin
          cp target/release/sysexts-manager sysexts-manager/usr/bin/sysexts-manager

      - name: "Build sysext: sysexts-manager"
        uses: ./.github/actions/build
        with:
          sysext: 'sysexts-manager'
          image: ${{ env.IMAGE }}

  build-aarch64:
    strategy:
      fail-fast: false
      matrix:
        release: ['41', '42', '43']
    runs-on: "ubuntu-24.04-arm"
    container:
      image: "ghcr.io/travier/sysexts-manager/buildroot:latest"
      options: "--privileged --security-opt label=disable --user 0:0"
    env:
      IMAGE: "quay.io/fedora-ostree-desktops/base-atomic:${{ matrix.release }}"
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v5

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

      - name: "Build sysexts-manager"
        run: |
          cargo build --release
          mkdir -p sysexts-manager/usr/bin
          cp target/release/sysexts-manager sysexts-manager/usr/bin/sysexts-manager

      - name: "Build sysext: sysexts-manager"
        uses: ./.github/actions/build
        with:
          sysext: 'sysexts-manager'
          image: ${{ env.IMAGE }}

  publish-latest:
    runs-on: "ubuntu-24.04"
    container:
      image: "ghcr.io/travier/sysexts-manager/buildroot:latest"
    # Run after both arch builds
    needs:
      - build-x86_64
      - build-aarch64
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v5

      - name: "Mark directory as safe"
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

      - name: "Gather all sysexts releases"
        uses: ./.github/actions/gather
        with:
          sysexts: 'sysexts-manager'
